const CONFIG = {
  "eventsLimit": 5,
  "includeFollowers": "yes",
  "includeRedemptions": "yes",
  "includeHosts": "yes",
  "minHost": 1,
  "includeRaids": "yes",
  "minRaid": 1,
  "includeSubs": "yes",
  "includeTips": "yes",
  "minTip": 1,
  "includeCheers": "yes",
  "minCheer": 1,
  "direction": "top",
  "textOrder": "nameFirst",
  "fadeoutTime": 10,
  "fontColor": "rgb(255, 255, 255)",
  "theme": "texture",
  "backgroundOpacity": 50,
  "backgroundColor": "rgba(119, 133, 255, 0.85)",
  "iconColor": "rgb(255, 255, 255, 255)",
  "locale": "en-US",
  "displayDuration": 10,
  "fontName": "Montserrat",
  "fontSize": 18,
  "widgetDuration": 5
}